name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ master ]  # ✅ Your current branch

jobs:
  laravel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, xml, curl, mysql

    - name: Install composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/pariswit/tablesfood.com
          git pull origin master     # ✅ changed from main to master
          composer install --no-dev
          php artisan migrate --force
          php artisan config:cache